{{- if .Values.playground.enabled }}
{{- with .Values.playground }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "llama-stack-playground.fullname" $ }}
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: http
      protocol: TCP
      name: llama-stack-playground
  selector:
    {{- include "llama-stack-playground.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}